version: '3'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./world/world.sql:/docker-entrypoint-initdb.d/world.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: world

