version: '3'
services:
  # main instance for testing
  postgres:
    image: postgres:11
    volumes:
      - ./world/world.sql:/docker-entrypoint-initdb.d/world.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: world
  # for testing password-free login
  trust:
    image: postgres:11
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: world
      POSTGRES_HOST_AUTH_METHOD: trust

