name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v2
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up cert permissions
        run: chmod 600 world/server.key
      - name: Start up Postgres instances
        run: docker-compose up
      - name: Run tests
        run: csbt headerCheck +test docs/paradox
      - name: Shut down Postgres instances
        run: docker-compose down
